import{hnlLogger}from"./hnl.logger.min.mjs";export const NAME="wpXMLSearch";let controller,signal;function searchWhenTyping(e){const input=e.target;const search=input.value.trim();const form=input.form;if(!search||search.length<2){form.xmlProps.DropdownHasData=false;form.xmlProps.Dropdown.classList.remove("show")}else if(!input.searched||input.searched!==search){hnlLogger.log(NAME,"Searching for: "+search);clearDropdownButKeepLoader(form.xmlProps.Dropdown);form.xmlProps.Dropdown.classList.add("show");
input.searched=form.xmlProps.Params.s=search;if(controller!==undefined)controller.abort();if("AbortController"in window){controller=new AbortController;signal=controller.signal}fetch(`${form.xmlProps.Uri}?${new URLSearchParams(form.xmlProps.Params)}`,{method:"GET",signal}).then(response=>response.json()).then(jsonData=>{clearDropdownButKeepLoader(form.xmlProps.Dropdown);form.xmlProps.Loader.classList.add("d-none");if(jsonData.length){form.xmlProps.DropdownHasData=true;for(const result of jsonData){const {post_title,
post_excerpt,guid,post_type}=result;form.xmlProps.Dropdown.appendChild(addListItem(post_title,post_excerpt,guid,post_type))}}else{const message=`Geen resultaten ${form.xmlProps.CatType}. Probeer een andere zoekterm.`;form.xmlProps.Dropdown.appendChild(addListItem(message));form.xmlProps.DropdownHasData=false}}).catch(error=>{hnlLogger.warn(NAME,error);clearDropdownButKeepLoader(form.xmlProps.Dropdown);const message=`Geen resultaten ${form.xmlProps.CatType}. Probeer een andere zoekterm.`;form.xmlProps.Dropdown.appendChild(addListItem(message));
form.xmlProps.DropdownHasData=false})}}function clearDropdownButKeepLoader(dropdownToClear){[...dropdownToClear.children].filter(child=>!child.classList.contains("loader")).forEach(child=>child.remove());dropdownToClear.querySelector(".loader").classList.remove("d-none")}function addListItem(title,description,link,category){const listItem=document.createElement("li");const linkItem=link?document.createElement("a"):document.createElement("span");const titleElement=description?document.createElement("h6"):
document.createElement("span");const descElement=document.createElement("small");let catBadge="";if(category==="faq_items")catBadge='<span class="badge badge-outlined badge-primary fw-normal me-2">FAQ</span>';titleElement.classList.add("mb-0");titleElement.textContent=title;descElement.classList.add("text-muted");linkItem.appendChild(titleElement);linkItem.appendChild(descElement);if(description)descElement.innerHTML=catBadge+description;if(link){linkItem.href=link.replace("&#038;","&");linkItem.setAttribute("title",
`${title} - Klik om verder te lezen`)}linkItem.classList.add("dropdown-item","overflow-hidden","text-truncate");listItem.appendChild(linkItem);return listItem}export function init(elements){elements.forEach(function(element){const input=element.querySelector(".xml-search-input");if(!input){hnlLogger.error(NAME,"Form has no search input");return}input.disabled=false;element.xmlProps={Dropdown:element.querySelector(".xml-search-autocomplete"),Loader:element.querySelector(".loader"),DropdownHasData:false,
Params:{},Uri:element.dataset.xmlUri,CatType:typeof element.dataset.xmlType!=="undefined"?element.dataset.xmlType==="faq_items"?" gevonden in veelgestelde vragen":"":""};for(const attr in element.dataset)if(attr.includes("xml")&&!attr.includes("xmlUri"))element.xmlProps.Params[attr.replace("xml","").toLowerCase()]=element.dataset[attr];if(Object.values(element.xmlProps).some(v=>v===undefined)){hnlLogger.error(NAME,"Not all required settings set");return}function hideOnBlur(e){if(!element.contains(e.target)){input.removeEventListener("keyup",
searchWhenTyping);document.body.removeEventListener("click",hideOnBlur);element.xmlProps.Dropdown.classList.remove("show")}}input.addEventListener("search",function(e){const search=input.value.trim();if(!search){element.xmlProps.DropdownHasData=false;element.xmlProps.Dropdown.classList.remove("show");clearDropdownButKeepLoader(element.xmlProps.Dropdown)}});input.addEventListener("focusin",function(e){input.addEventListener("keyup",searchWhenTyping);document.body.addEventListener("click",hideOnBlur);
element.xmlProps.Dropdown.classList.toggle("show",element.xmlProps.DropdownHasData)})})};
