import{FpsCounter,EasedMeanCalculator}from"./hnl.helpers.mjs?debug=true";export const NAME="dynamicMotionBlur";const defaults={transitionTime:60,speedThresh:1,fps:60,scroller:{},events:{scrollStart:"scrollStart",scrolling:"scrolling",scrollStop:"scrollStop"}};export function init(elements){elements.forEach((elem,index)=>{const options={...defaults};options.index=index;options.easer=new EasedMeanCalculator;setupElement(elem,options)})}function setupElement(elem,options){elem.dispatcher=function(eventName,
eventDetails){const event=new CustomEvent(eventName,{detail:eventDetails,bubbles:true,cancelable:true});this.dispatchEvent(event)};options.filter=createSVGFilter(options);elem.style.setProperty("--blur-filter",`url('#${options.filter.filterId}')`);elem.addEventListener("scroll",e=>{handleScroll(elem,options,e)});new FpsCounter(fps=>{options.fps=fps;const event=new CustomEvent("fpsUpdate",{detail:options,bubbles:true,cancelable:true});elem.dispatchEvent(event)});setupEvents(elem,options)}function handleScroll(elem,
options){if(!options.scroller.scrolling){options.scroller.scrolling=true;options.scroller.horizontal=elem.dataset.scrollDirection==="horizontal";options.scroller.width=elem.offsetWidth;options.scroller.height=elem.offsetHeight;options.factor=getPerformanceScale(elem,options);options.shutterAngle=getShutterAngle(elem);options.speed=options.blur=0;options.scroller.lastScrollLeft=elem.scrollLeft;options.scroller.lastScrollTop=elem.scrollTop;options.easer.reset("speed");options.transitionTime=Math.floor(1E3/
options.fps*5);elem.dispatcher(options.events.scrollStart,options)}clearTimeout(options.scroller.scrollEndTimer);const timeOut=(options.scroller.horizontal?elem.scrollLeft%options.scroller.width===0:elem.scrollTop%options.scroller.height===0)?0:150;options.scroller.scrollEndTimer=setTimeout(()=>{if(options.scroller.scrolling){options.scroller.scrolling=false;cancelAnimationFrame(options.scroller.watcher);options.scroller.watcher=null;options.scroller.snapped=!timeOut;elem.dispatcher(options.events.scrollStop,
options)}},timeOut);if(!options.scroller.watcher){options.scroller.prevTimeStamp=performance.now();function watcher(timestamp){options.scroller.thisTimeStamp=timestamp;const scrollLeftDistance=elem.scrollLeft-(options.scroller.lastScrollLeft||0);const scrollTopDistance=elem.scrollTop-(options.scroller.lastScrollTop||0);options.distance=scrollLeftDistance||scrollTopDistance;elem.dispatcher(options.events.scrolling,options);options.scroller.lastScrollLeft=elem.scrollLeft;options.scroller.lastScrollTop=
elem.scrollTop;options.scroller.prevTimeStamp=timestamp;options.scroller.watcher=requestAnimationFrame(watcher)}options.scroller.watcher=requestAnimationFrame(watcher)}}function setupEvents(elem,options){for(const event in options.events)elem.addEventListener(event,event=>{handleCustomEvent(event,elem,options)})}function calculateStandardDeviation(elem,options){return options.scroller.horizontal?`${options.blur},0`:`0,${options.blur}`}function updateBlurEffect(elem,options){options.filter.adjust(calculateStandardDeviation(elem,
options),options.transitionTime)}function getPerformanceScale(elem,options){elem.style.removeProperty("--scaler-perf");return window.getComputedStyle(elem).getPropertyValue("--scaler-perf")}function getShutterAngle(elem){return!isNaN(parseInt(elem.dataset.shutterAngle,10))?parseInt(elem.dataset.shutterAngle,10):180}function handleCustomEvent(event,elem,options){switch(event.type){case options.events.scrollStart:elem.classList.add("hnl-scrolling");break;case options.events.scrolling:case options.events.scrollStop:options.speed=
event.type!==options.events.scrollStop?options.easer.getValue(Math.abs(options.distance)/(options.scroller.thisTimeStamp-(options.scroller.prevTimeStamp||0)),"speed"):0;options.blur=calcBlur(options.speed,options.shutterAngle,options.fps)/options.factor;elem.dataset.speed=options.speed.toString();elem.dataset.distance=options.distance;updateBlurEffect(elem,options);elem.classList.toggle("hnl-scrolling",event.type!==options.events.scrollStop);elem.classList.toggle("hnl-motionblurring",options.speed>
options.speedThresh&&event.type===options.events.scrolling);break;default:console.warn(`Unhandled event type: ${event.type}`);break}}function calcBlur(speed,shutter,fps=60){const deviationRatio=1/3;const exposureTimePerFrame=1E3/fps*(fps/24)/(360/shutter);return exposureTimePerFrame*speed*deviationRatio/2}function createSVGFilter(options){const ns="http://www.w3.org/2000/svg";const filterId=`motionblur-filter-${options.index}`;const stdDeviationId=`motionblur-stddeviation-${options.index}`;const animatorId=
`motionblur-animator-${options.index}`;const svg=document.createElementNS(ns,"svg");svg.setAttribute("class","filters");svg.setAttribute("xmlns",ns);svg.setAttribute("id",`filter-svg-${options.index}`);const defs=document.createElementNS(ns,"defs");const filter=document.createElementNS(ns,"filter");filter.setAttribute("id",filterId);const feGaussianBlur=document.createElementNS(ns,"feGaussianBlur");feGaussianBlur.setAttribute("in","SourceGraphic");feGaussianBlur.setAttribute("id",stdDeviationId);
feGaussianBlur.setAttribute("edgeMode","duplicate");const animate=document.createElementNS(ns,"animate");animate.setAttribute("attributeName","stdDeviation");animate.setAttribute("repeatCount","1");animate.setAttribute("fill","freeze");animate.setAttribute("id",animatorId);feGaussianBlur.appendChild(animate);filter.appendChild(feGaussianBlur);defs.appendChild(filter);svg.appendChild(defs);document.body.appendChild(svg);return{filterId,prevDev:null,adjust:function(stdDeviation,transitionTime=options.transitionTime){animate.setAttribute("dur",
`${transitionTime}ms`);animate.setAttribute("values",`${stdDeviation};0,0`);animate.beginElementAt(0)}}};
