import eventHandler from"./hnl.eventhandler.mjs";import{hnlLogger}from"./hnl.logger.mjs";import{toMS}from"./hnl.helpers.mjs";import{debounceThis}from"./hnl.debounce.mjs";import fpsCounter from"./hnl.fps.mjs";export const NAME="motionBlur";const frameInterval=60;const spindownTime=400;const blurThresh=.3;const scrollStart=new Event("scrollStart");const scrollStop=new Event("scrollStop");const blurStart=new Event("blurStart");const blurStop=new Event("blurStop");function vwTOpx(value){value=parseFloat(value);
return(window.innerWidth||document.element.clientWidth||document.getElementsByTagName("body")[0].clientWidth)*value/100}function motionBlur(distance,speed){const time=distance/speed;const blurAmount=time*speed;const blurFactor=.8;return blurAmount>0?Math.floor(blurAmount/blurFactor*10)/10:0}function getFrameBlurValues(bezierFormula,range,time,direction="horizontal"){if(!bezierFormula)return;const duration=time/1E3;const numFrames=Math.round(duration*120);const blurValues=[];let yNext=null;for(let i=
0;i<=numFrames;i++){const t=i/numFrames;const yValue=yNext?yNext:range[0]+cubicBezier(bezierFormula,t)*(range[1]-range[0]);yNext=i+1<=numFrames?range[0]+cubicBezier(bezierFormula,(i+1)/numFrames)*(range[1]-range[0]):yValue;if(yNext!==null){const dist=Math.abs(yNext-yValue);const speed=Math.round(dist/(duration/numFrames));if(direction==="horizontal")blurValues.push(`${motionBlur(dist,speed)},0`);else if(direction==="vertical")blurValues.push(`0,${motionBlur(dist,speed)}`)}}return blurValues}function cubicBezier([x1,
y1,x2,y2],t){const cx=3*x1;const bx=3*(x2-x1)-cx;const ax=1-cx-bx;const cy=3*y1;const by=3*(y2-y1)-cy;const ay=1-cy-by;function sampleCurveX(t){return((ax*t+bx)*t+cx)*t}function solveCurveX(x,epsilon){let t2=x,d2,i;for(i=0;i<8;i++){const x2=sampleCurveX(t2)-x;if(Math.abs(x2)<epsilon)return t2;d2=(3*ax*t2+2*bx)*t2+cx;if(Math.abs(d2)<1E-6)break;t2-=x2/d2}const t1=t2-x2/d2;return t1}function sampleCurveY(t){return((ay*t+by)*t+cy)*t}const t1=solveCurveX(t,1E-6);return sampleCurveY(t1)}function extractCubicBezier(elem){let match=
window.getComputedStyle(elem)["transition"].match(/\w\s.*\scubic-bezier\(([^)]+)\)/);if(match)return match[1].split(",").map(parseFloat);else{const transitionTimings={"ease":[.25,.1,.25,1],"linear":[0,0,1,1],"ease-in":[.42,0,1,1],"ease-out":[0,0,.58,1],"ease-in-out":[.42,0,.58,1]};match=window.getComputedStyle(elem)["transition"].match(/\w\s\S+\s([\w\-?]+)\s?/);if(match)return transitionTimings[match[1]]?transitionTimings[match[1]]:transitionTimings["ease-in-out"];else return undefined}}function createSVGFilter(element,
index,direction){const ns="http://www.w3.org/2000/svg";const idx=`filter-${index}`;const filterRef=`motionblur-${idx}`;const svg=document.createElementNS(ns,"svg");svg.setAttribute("class","filters");svg.setAttribute("xmlns",ns);svg.setAttribute("id",idx);const def=document.createElementNS(ns,"defs");const filter=document.createElementNS(ns,"filter");filter.setAttribute("x","0");filter.setAttribute("y","0");filter.setAttribute("width","100%");filter.setAttribute("height","100%");filter.setAttribute("color-interpolation-filters",
"auto");filter.setAttribute("id",filterRef);const gb=document.createElementNS(ns,"feGaussianBlur");gb.setAttribute("in","SourceGraphic");gb.setAttribute("id",`motionblur-params-${idx}`);gb.setAttribute("stdDeviation","0,0");gb.setAttribute("edgeMode","wrap");const animator=document.createElementNS(ns,"animate");animator.setAttribute("attributeName","stdDeviation");animator.setAttribute("begin","indefinite");animator.setAttribute("values","0");animator.setAttribute("dur","250ms");animator.setAttribute("repeatCount",
"1");animator.setAttribute("fill","remove");animator.setAttribute("id",`motionblur-animator-${idx}`);gb.appendChild(animator);filter.appendChild(gb);def.appendChild(filter);svg.appendChild(def);document.body.appendChild(svg);element.style.setProperty("--blur-filter",`url('#${filterRef}')`);animator.adjust=function(blurTrigger){const style=window.getComputedStyle(blurTrigger);const moveAmount=style.getPropertyValue("--move-amount").includes("px")?parseInt(style.getPropertyValue("--move-amount"),10):
vwTOpx(style.getPropertyValue("--move-amount"));const moveDuration=parseFloat(toMS(style.getPropertyValue("transition-duration").split(",")[0]));const frameValues=getFrameBlurValues(extractCubicBezier(blurTrigger),[0,moveAmount],moveDuration,direction);if(frameValues){animator.setAttribute("values",frameValues.join(";"));animator.setAttribute("dur",`${Math.floor((moveDuration?moveDuration:250)/2)}ms`)}};animator.adjustFixedBlur=function(blurTrigger,value,dir){animator.remove();value=Math.round(value*
10)/10;const setValue=value?dir==="horizontal"?[value,0]:[0,value]:[0,0];gb.setAttribute("stdDeviation",setValue.join(","));if(value<=blurThresh&&blurTrigger.blurring){blurTrigger.blurring=false;blurTrigger.dispatchEvent(blurStop)}else if(value>blurThresh&&!blurTrigger.blurring){blurTrigger.blurring=true;blurTrigger.dispatchEvent(blurStart)}};return animator}function getXY(elem){elem.prevXY=elem.prevXY?elem.prevXY:[0,0];const transform=window.getComputedStyle(elem).getPropertyValue("transform");const xy=
(transform==="none"?"matrix(1, 0, 0, 1, 0, 0)":transform).split(",").slice(-2).map(v=>parseFloat(v));const direction=xy[0]!==elem.prevXY[0]?"horizontal":xy[1]!==elem.prevXY[1]?"vertical":"unknown";elem.prevXY=xy;return[xy,direction]}function calcBlur(speed,shutter){let shutterSpeed=60*360/shutter;let exposure=1E3/shutterSpeed;return speed*exposure/2||0}let prevBlur;function getBlur(speed,shutter,perf){let blur=calcBlur(speed,shutter);blur=Math.round(blur*10)/10;let dampenedBlur=prevBlur?(prevBlur+
blur)/2:blur;prevBlur=blur;return Math.round(blur/perf*10)/10}export function init(elements){elements.forEach((elem,index)=>{elem.blurEnabled=false;elem.blurTrigger=typeof elem.dataset.blurTrigger!=="undefined"&&document.getElementById(elem.dataset.blurTrigger)!==null?document.getElementById(elem.dataset.blurTrigger):elem;elem.getBlurDirection=()=>{return typeof elem.dataset.blurDirection!=="undefined"?elem.dataset.blurDirection:typeof elem.dataset.scrollDirection!=="undefined"?elem.dataset.scrollDirection:
"horizontal"};elem.blurAnimator=createSVGFilter(elem,index,elem.getBlurDirection());if(elem.dataset.blurType==="speed"){function runStart(e){if(!e.target.scrolling){e.target.dispatchEvent(scrollStart);e.target.scrolling=true}elem.classList.toggle("hnl-scrolling",e.target.scrolling)}function runStartWhile(e){const elem=e.target;const horizontal=elem.getBlurDirection()==="horizontal";const now=performance.now();const time=now-(elem.prevTimeStamp?elem.prevTimeStamp:0);const distance=horizontal?elem.scrollLeft-
(elem.prevScrollLeft?elem.prevScrollLeft:0):elem.scrollTop-(elem.prevScrollTop?elem.prevScrollTop:0);elem.scrollSpeed=Math.abs(distance)/time;let pxRemain=horizontal?elem.scrollLeft%elem.offsetWidth:elem.scrollTop%elem.offsetHeight;pxRemain=pxRemain===0?0:distance>0?pxRemain:(horizontal?elem.offsetWidth:elem.offsetHeight)-pxRemain;const timeOut=pxRemain===0?0:150;const multiplier=!isNaN(parseInt(window.getComputedStyle(e.target).getPropertyValue("--scaler-perf"),10))?parseInt(window.getComputedStyle(e.target).getPropertyValue("--scaler-perf"),
10):1;const shutterangle=!isNaN(parseInt(e.target.dataset.shutterAngle,10))?parseInt(e.target.dataset.shutterAngle,10):180;clearTimeout(elem.scrollTimeout);elem.scrollTimeout=setTimeout(function(){runStop(e);if(!timeOut);else;},timeOut);elem.blurAmount=getBlur(elem.scrollSpeed,shutterangle,multiplier);const decrease=e.target.blurAmount/(spindownTime/frameInterval);const numCompleteFrames=(spindownTime-spindownTime%frameInterval)/frameInterval;let x=0;if(elem.spinDown){clearInterval(elem.spinDown);
elem.spinDown=null}elem.spinDown=setInterval(()=>{const complete=x/numCompleteFrames;const bezierMultiplier=complete===1?1:1-Math.pow(2,-10*complete);const blur=e.target.blurAmount-e.target.blurAmount*bezierMultiplier;elem.blurAnimator.adjustFixedBlur(elem.blurTrigger,blur,elem.getBlurDirection());if(blur<=0||complete>=1){e.target.blurring=false;e.target.dispatchEvent(blurStop);clearInterval(elem.spinDown);elem.spinDown=null}if(complete>=.5)e.target.classList.remove("hnl-motionblurring");x++},frameInterval);
e.target.classList.toggle("hnl-motionblurring",e.target.blurring);e.target.classList.toggle("hnl-scrolling",elem.scrollSpeed>0);elem.prevScrollTop=elem.scrollTop;elem.prevScrollLeft=elem.scrollLeft;elem.prevTimeStamp=now}function runStop(e){e.target.dispatchEvent(scrollStop);e.target.blurring=e.target.scrolling=false;e.target.classList.remove("hnl-motionblurring","hnl-scrolling")}elem.blurTrigger.addEventListener("scroll",debounceThis(e=>{if(e.debounceType==="start")runStart(e);runStartWhile(e)},
{threshold:frameInterval,execStart:true,execWhile:true,execDone:false}))}else if(!elem.dataset.blurType||elem.dataset.blurType==="fixed"){elem.transDelay=parseInt(window.getComputedStyle(elem.blurTrigger).getPropertyValue("--transition-delay"),10)||0;elem.blurTrigger.prevXY=getXY(elem.blurTrigger);elem.blurTrigger.addEventListener("transitionstart",e=>{if(e.propertyName==="transform"&&elem.blurEnabled&&e.target===elem.blurTrigger)if(elem.getBlurDirection()===getXY(elem.blurTrigger)[1])setTimeout(()=>
{elem.blurAnimator.beginElement();elem.classList.add("hnl-motionblurring")},elem.transDelay)},{capture:false});elem.blurTrigger.addEventListener("transitionend",e=>{if(e.propertyName==="transform"&&elem.blurEnabled&&e.target===elem.blurTrigger){elem.classList.remove("hnl-motionblurring");elem.blurTrigger.prevXY=getXY(elem.blurTrigger)}},{capture:false})}});function prepare(){elements.forEach((elem,index)=>{elem.blurAnimator.adjust(elem.blurTrigger);elem.blurEnabled=true})}eventHandler.addListener("startResize",
e=>{elements.forEach((elem,index)=>{elem.blurEnabled=false})});eventHandler.addListener("endResize",prepare);eventHandler.addListener("docReady",prepare)};
